### ISSUE TITLE
Updating badges in README.md

### ISSUE THREAD

**Issue by AstroAirafar** [solve-ease/community-website#18]
### Adding badges for forks, stars, contributors etc. to make the website more expressive and elegant.

![image](https://github.com/user-attachments/assets/2d3f82ef-e536-45c9-8787-7d41f0850991)

**Comment by 4darsh-Dev** [comment]
i've added review, fix the required changes

**Comment by AstroAirafar** [comment]
Required changes has been made. Issue has been resolved. Closing the issue.

**Comment by 4darsh-Dev** [comment]
Hey @AstroAirafar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
