### ISSUE TITLE
Add issue_template.md

### ISSUE THREAD

**Issue by AstroAirafar** [solve-ease/community-website#23]
Creating and adding a new custom issue template for this project.

**Comment by AstroAirafar** [comment]
Issue resolved. Closed.

**Comment by 4darsh-Dev** [comment]
Hey @AstroAirafar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
