### ISSUE TITLE
Add PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by AstroAirafar** [solve-ease/community-website#25]
### Creating and adding a Pull Request Template for the project to facilitate raising a pull request.

**Comment by AstroAirafar** [comment]
Issue resolved successfully. Closed.

**Comment by 4darsh-Dev** [comment]
Hey @AstroAirafar ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
