### ISSUE TITLE
Add Login and Contact page to StudentzSynergy website

### ISSUE THREAD

**Issue by AmanSingh494** [solve-ease/community-website#28]
### Issue Type

- [x] Feature Request

### Description

The StudentzSynergy website doesn't have a Login and Contact page 

### Proposed Solution (For Feature Requests)

Creation of Login and Contact page

### Tasks

- [x] Create the Login page using Html, Css and Js.
- [x] Create the Contact page using Html, Css and Js.

**Comment by AmanSingh494** [comment]
I would like to work on this issue, So please assign it to me.

**Comment by 4darsh-Dev** [comment]
assigned to you @AmanSingh494

**Comment by 4darsh-Dev** [comment]
@AmanSingh494  any update, 
you've havent raised any pr yet?

**Comment by AmanSingh494** [comment]
> @AmanSingh494 any update, you've havent raised any pr yet?

I have made login page and working on contact page.

**Comment by 4darsh-Dev** [comment]
okay i have raise a pr for home page #30 
@AmanSingh494

**Comment by 4darsh-Dev** [comment]
any update @AmanSingh494 ?

**Comment by AmanSingh494** [comment]
> any update @AmanSingh494 ?

I will create a pull request today

**Comment by 4darsh-Dev** [comment]
Hey @AmanSingh494 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by AmanSingh494** [comment]
> Hey @AmanSingh494 ! Thank you so much for your raising the issue💗 It’s all yours, you can come anytime again and make some contributions! 🚀 Alone, we can do little, but together we can do so much! 😇

Thanks @4darsh-Dev , I would love to make more contributions.
