### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by D-coder001** [solve-ease/community-website#3]
To make it easier for everyone to contribute to our project, we should add a `CONTRIBUTING.md` file. 
This file will provide guidelines on how to contribute, including coding standards, branch management, and the process for submitting pull requests. 
By having this file, we can ensure that contributions are consistent and that new contributors have a clear understanding of our project's workflow.
@4darsh-Dev

**Comment by 4darsh-Dev** [comment]
assigned to you @D-coder001
