### ISSUE TITLE
Addition of preloader

### ISSUE THREAD

**Issue by devish041111** [solve-ease/community-website#31]
##Description
Create a preloader for frontend of the website using HTML,CSS and javascript. 
The components should be movable with javascript and CSS animations

credits : *Isha* 

### SS 
![Screenshot 2024-07-17 190914](https://github.com/user-attachments/assets/e02bcb08-dc20-454d-ae74-cd8f20d3f851)

### Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Question

### Checklist

- [x] I have searched the existing issues for duplicates.
- [ ] I have provided detailed steps to reproduce the bug (if applicable).
- [ ] I have described the expected and actual behavior (if applicable).
- [x] I have provided a proposed solution (for feature requests).
- [ ] I have included relevant environment details.

**Comment by Dharmi-dev** [comment]
I am really excited to work on the preloader  for our website and will do my best
please assign this issue to me

**Comment by 4darsh-Dev** [comment]
assigned to you @Dharmi-dev, complete on given time.

**Comment by 4darsh-Dev** [comment]
Hey @ish041111 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
