### ISSUE TITLE
[FEAT]  Footer for the website

### ISSUE THREAD

**Issue by 4darsh-Dev** [solve-ease/community-website#37]
## Description
1. Adding footer for the website with useful links and nav items, frontend, 
2. Creative wavey effect with javascript and css
3. Adding a newsletter subscription form with HTML 

> [!IMPORTANT]
> Must be Responsive on all devices.

> [!CAUTION]
> Follow code standards.

**Comment by 4darsh-Dev** [comment]
https://www.pinterest.com/pin/740982944955420392/

**Comment by Dharmi-dev** [comment]
I am very excited to resolve this issue and  will make a wonderful footer for this project,
Please assign this issue to me
![Screenshot 2024-07-24 120233](https://github.com/user-attachments/assets/87de0e61-886a-44b1-b866-4a62c318e686)
![Screenshot 2024-07-24 120211](https://github.com/user-attachments/assets/4ab865db-af0e-4f2f-89a8-7fbc7d7cdd3b)
samples, if any you like

**Comment by 4darsh-Dev** [comment]
@Dharmi-dev , 
assigned to you, go with dehub first design, 
1. use navbar color in place of pink one, 
2. use fontawesome icons , not any other
3. use mailto: in href anchor tag for subscribing email

**Comment by 4darsh-Dev** [comment]
@Dharmi-dev  close this now.
