### ISSUE TITLE
TERMS AND CONDITIONS

### ISSUE THREAD

**Issue by anjali20040322** [solve-ease/community-website#43]
### Issue Type

- [ ] Bug Report

- [x] Feature Request

- [ ] Question

### Description

Adding content for terms and conditions and updating documentations.
[TERMS AND CONDITIONS.txt](https://github.com/user-attachments/files/16365664/TERMS.AND.CONDITIONS.txt)

### Environment

- **OS:** [e.g., Windows, MacOS, Linux]
- **Browser:** [e.g., Chrome, Firefox, Safari]
- **Version:** [e.g., 1.0.0]

### Checklist

- [ ] I have searched the existing issues for duplicates.
- [ ] I have provided detailed steps to reproduce the bug (if applicable).
- [ ] I have described the expected and actual behavior (if applicable).
- [x] I have provided a proposed solution (for feature requests).
- [x] I have included relevant environment details.

**Comment by 4darsh-Dev** [comment]
@anjali20040322  attachment link or file?

**Comment by anjali20040322** [comment]
> ### Issue Type
> * [ ]  Bug Report
> * [ ]  Feature Request
> * [ ]  Question
> 
> ### Description
> Adding content for terms and conditions and updating documentations. 
> 
[TERMS AND CONDITIONS.txt](https://github.com/user-attachments/files/16366287/TERMS.AND.CONDITIONS.txt)

> ### Steps to Reproduce (For Bug Reports)
> ### Expected Behavior (For Bug Reports)
> ### Actual Behavior (For Bug Reports)
> ### Proposed Solution (For Feature Requests)
> ### Additional Context
> ### Environment
> * **OS:** [e.g., Windows, MacOS, Linux]
> * **Browser:** [e.g., Chrome, Firefox, Safari]
> * **Version:** [e.g., 1.0.0]
> 
> ### Checklist
> * [ ]  I have searched the existing issues for duplicates.
> * [ ]  I have provided detailed steps to reproduce the bug (if applicable).
> * [ ]  I have described the expected and actual behavior (if applicable).
> * [x]  I have provided a proposed solution (for feature requests).
> * [x]  I have included relevant environment details.
> 
> ### Additional Comments

**Comment by 4darsh-Dev** [comment]
Hey @anjali20040322 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
