### ISSUE TITLE
Privacy policy for our website 

### ISSUE THREAD

**Issue by JhalakTech-coder** [solve-ease/community-website#44]
I'm attaching the privacy policy for our website. Pls have a look to it. 
[privacy policy(html code).txt](https://github.com/user-attachments/files/16376265/privacy.policy.html.code.txt)

**Comment by 4darsh-Dev** [comment]
Hey @JhalakTech-coder ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
