### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Dharmi-dev** [solve-ease/community-website#8]
lets make a classic and simple home page having an overview of the whole project with a little touch of responsiveness
home page should contain sections like:
1.navbar
2.landing page
3.Our services
4.testimonials
5.Subscribe section
6.footer

**Comment by Dharmi-dev** [comment]
I am very curious to work on this issue,
I will fulfill all the need given above and make a simple and classic home page for the community
Please assign this issue to me

**Comment by 4darsh-Dev** [comment]
sure @Dharmi-dev collab with design and content team in discord and tell them your needs .

**Comment by 4darsh-Dev** [comment]
@Dharmi-dev design is ready for landing and login/ register, pages, 
you can start working.

**Comment by Dharmi-dev** [comment]
sure! I will do my best

**Comment by 4darsh-Dev** [comment]
Hey @Dharmi-dev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
